name: "Setup"

inputs:
  cache-venv:
    default: "false"
  cache-yarn:
    default: "false"
  cache-db:
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        architecture: "x64"

    - name: Setup Pipenv
      shell: bash
      run: |
        pip install pipenv
        python --version ; pip --version ; pipenv --version

    - name: Cache the node_modules
      if: inputs.cache-yarn == 'true'
      id: cache-yarn
      uses: actions/cache@v4
      with:
        path: ./node_modules
        key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          node-modules-${{ runner.os }}-

    - name: Cache the node_modules for retry-cli
      if: inputs.cache-yarn != 'true'
      id: cache-yarn-retry-cli
      uses: actions/cache@v4
      with:
        path: ./node_modules
        key: node-modules-retry-cli

    - name: Cache .venv
      if: inputs.cache-venv == 'true'
      id: cache-venv
      uses: actions/cache@v4
      with:
        path: ./.venv
        key: venv-${{ runner.os }}-${{ hashFiles('./Pipfile.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-

    - name: Check .venv
      id: check-venv
      shell: bash
      run: |
        if (pipenv run python3 -c "import django"); then
          echo "result=true" >> $GITHUB_OUTPUT
        else
          echo "result=false" >> $GITHUB_OUTPUT
          # 일주일이 지난 PR은 GitHub에 의해 .venv 캐시가 삭제되므로 재설치가 필요하다.
          # https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
          rm -rf .venv
        fi

    - name: zz deps_django
      if: inputs.cache-venv == 'true' && (steps.cache-venv.outputs.cache-hit != 'true' || steps.check-venv.outputs.result != 'true')
      shell: bash
      run: |
        ./zz deps_django

    - name: Setup Node 20
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Run Yarn Install
      if: inputs.cache-yarn == 'true' && steps.cache-yarn.outputs.cache-hit != 'true'
      shell: bash
      run: |
        ./zz deps_react

    - name: Setup retry command
      if: inputs.cache-yarn != 'true' && steps.cache-yarn-retry-cli.outputs.cache-hit != 'true' # yarn 전체 설치를 안 하는 경우 별도로 retry-cli만 설치한다.
      shell: bash
      run: |
        yarn add --dev -W retry-cli@^0.7.0
        yarn patch-package

    - name: Initialize Lerna
      if: steps.cache-yarn.outputs.cache-hit == 'true' || steps.cache-yarn-retry-cli.outputs.cache-hit == 'true'
      shell: bash
      run: |
        ./zz deps_react_init

    - name: Cache DB migration datas
      if: inputs.cache-db == 'true'
      id: cache-db
      uses: actions/cache@v4
      with:
        path: ./db-volume.tar
        key: db-${{ runner.os }}-${{ hashFiles('zuzu/db/migrations/0*') }}
        restore-keys: |
          db-${{ runner.os }}-

    - name: Extract the compressed DB migration datas
      if: inputs.cache-db == 'true' && steps.cache-db.outputs.cache-hit == 'true'
      shell: bash
      run: |
        sudo tar -xvf db-volume.tar

    - name: Compress the DB migration datas
      if: inputs.cache-db == 'true' && steps.cache-db.outputs.cache-hit != 'true'
      shell: bash
      run: |
        docker-compose -f ./docker/testing.yaml up -d db
        for _ in $(seq 3); do yarn retry -t 1000 --max-timeout=60000 ./zz db_isready; sleep 1; done

        ./zz migrate --no-input
        ./zz backupdb postgres test_postgres

        # actions/cache에서는 'docker' usergroup이 소유하고 있는 파일에 접근할 수 없어, 부득이하게 Docker volume의 압축파일을 생성하여 캐시한다.
        # See https://github.com/actions/cache/issues/31
        sudo tar -cvf db-volume.tar ./db-volume
