name: "Setup"

inputs:
  cache-venv:
    default: "false"
  cache-yarn:
    default: "false"
  cache-db:
    default: "false"
  github-token:
    default: ""
  db-snapshot-artifact-run-id:
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: kodebox-io/captain-setup-action/setup-node@dev
      with:
        install-zuzu-dependencies: ${{ inputs.cache-yarn }}

    - uses: kodebox-io/captain-setup-action/setup-python@dev
      with:
        install-zuzu-dependencies: ${{ inputs.cache-venv }}

    - uses: kodebox-io/captain-setup-action/setup-db-with-artifact@dev
      if: inputs.cache-db == 'true'
      with:
        github-token: ${{ inputs.github-token }}
        db-snapshot-artifact-run-id: ${{ inputs.db-snapshot-artifact-run-id }}
