name: "Setup Python"

inputs:
  install-zuzu-dependencies:
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        architecture: "x64"

    - name: Setup Pipenv
      shell: bash
      run: |
        pip install pipenv
        python --version ; pip --version ; pipenv --version

    - name: Cache .venv
      if: inputs.install-zuzu-dependencies == 'true'
      id: cache-venv
      uses: actions/cache@v4
      with:
        path: ./.venv
        key: venv-${{ runner.os }}-${{ hashFiles('./Pipfile.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-

    - name: Check .venv
      id: check-venv
      shell: bash
      run: |
        if (pipenv run python3 -c "import django"); then
          echo "result=true" >> $GITHUB_OUTPUT
        else
          echo "result=false" >> $GITHUB_OUTPUT
          # 일주일이 지난 PR은 GitHub에 의해 .venv 캐시가 삭제되므로 재설치가 필요하다.
          # https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
          rm -rf .venv
        fi

    - name: zz deps_django
      if: inputs.install-zuzu-dependencies == 'true' && (steps.cache-venv.outputs.cache-hit != 'true' || steps.check-venv.outputs.result != 'true')
      shell: bash
      run: |
        ./zz deps_django
